# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55940af75835a5ee2a92cbaf5d60f371ae726d70d4e050a044af9420c478645bb9890f81b0d22f2e61d10c448251b816852fb14d0673e43436cd1cbd959b43f5

test:
  secret_key_base: 833d0cfd249fc1a23105d5c3af504521d61462a91afe4a2f04c0319136ef4f7c9e700aa3dd3347c3322c6c72b8f2745d0e0c7a1b8b44a8d95835f2443795318a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
